# -*- coding: utf-8 -*-
"""feature_scaling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uWm6ESAWlIVH612qs7R4Wkqi3IvDguam
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
uploaded = files.upload()

import io

data_set = pd.read_csv(io.BytesIO(uploaded['feature scaling.csv']))
data_set.head()

x = data_set.iloc[:, 1:3].values

from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler(feature_range = (0,1))
x_after_min_max_scaler = min_max_scaler.fit_transform(x)

x_after_min_max_scaler

Standardisation = preprocessing.StandardScaler()
x_after_sd = Standardisation.fit_transform(x)

x_after_sd